/* NOME, EMAIL, NUMERO, ESTADO*/
/*IFNULL*/
IFNULL(Parametro,'Retorno');

SELECT C.NOME, IFNULL(C.EMAIL,'NÃO TEM EMAIL') AS 'E-MAIL', E.ESTADO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

/*VIEWS*/
SELECT C.NOME, C.SEXO, IFNULL(C.EMAIL,'NÃO TEM EMAIL') AS 'E-MAIL', T.TIPO, T.NUMERO, E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

CREATE VIEW RELATORIO AS
SELECT C.NOME, C.SEXO, IFNULL(C.EMAIL,'NÃO TEM EMAIL') AS 'E-MAIL', T.TIPO, T.NUMERO, E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

SELECT * FROM RELATORIO;
SHOW TABLES;

/*APAGANDO UMA VIEW*/
DROP VIEW RELATORIO;

/*INSERINDO UM PREFIXO*/
CREATE VIEW V_RELATORIO AS
SELECT C.NOME, C.SEXO, IFNULL(C.EMAIL,'NÃO TEM EMAIL') AS 'E-MAIL', T.TIPO, T.NUMERO, E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

SELECT NOME, NUMERO, ESTADO
FROM V_RELATORIO;

/*INSERT, UPDATE E DELETE- DML COM VIEWS */

INSERT INTO V_RELATORIO VALUES ('ANDREIA','F','ANDREIA@UOL.COM.BR','CEL','92298667','CENTRO','VITORIA','ES');

 ERROR 1394 (HY000): Can not insert into join view 'comercio.v_relatorio' without fields list
 
 /*ORDER BY */
 
SELECT * FROM ALUNOS
ORDER BY NUMERO;

SELECT * FROM ALUNOS
ORDER BY 1; /*ORDENAR PELA COLUNA 1*/

SELECT * FROM ALUNOS
ORDER BY 2; /*ORDENAR PELA COLUNA 2*/

/*ORDENANDO POR MAIS DE UMA COLUNA*/ 
SELECT * FROM ALUNOS
ORDER BY NUMERO,NOME;

/*ORDER BY DESC / ASC */
SELECT * FROM ALUNOS
ORDER BY 1 ASC;

SELECT * FROM ALUNOS
ORDER BY 1 DESC;

SELECT * FROM ALUNOS
ORDER BY 1, 2 DESC;

SELECT * FROM ALUNOS
ORDER BY 1 DESC, 2 DESC;

/* ORDENADO COM JOINS */
SELECT C.NOME, C.SEXO, IFNULL(C.EMAIL,'NÃO TEM EMAIL') AS 'E-MAIL', T.TIPO, T.NUMERO, E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;
ORDER BY 1;

SELECT * FROM V_RELATORIO
ORDER BY 1;
 