/* DELETANDO REGISTROS COM A CLAUSULA DELETE */

DELETE FROM CLIENTE;

SELECT COUNT(*) FROM CLIENTE; /* TOTAL 6*/

SELECT COUNT(*) CLIENTE /* TOTAL A SER DELETADO 1*/
WHERE NOME = 'ANA';

DELETE FROM CLIENTE
WHERE NOME = 'ANA';

SELECT * FROM CLIENTE
WHERE NOME = 'CARLA'
AND EMAIL = 'LILIAN@HOTMAIL.COM';

DELETE FROM CLIENTE
WHERE NOME = 'CARLA'
AND EMAIL = 'LILIAN@HOTMAIL.COM';