/* RELACIONAMENTOS 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA*/
/* RELACIONAMENTOS 1 X N A CHAVE ESTRANGEIRA FICA SEMPRE NA CARDINALIDADE N*/

INSERT INTO CLIENTE VALUES(NULL,'JOÃO','M','JOÃO@GMAIL.COM','28336273832');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOS@IG.COM','32566578996');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@HOTMAIL.COM','12345479895');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'28336273832');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@GMAIL.COM','26548968936');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','F','CELIA@UOL.COM','45698632669');

INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIA SA','CENTRO','B. HORIZONTE','MG',5);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA PRESIDENTE VARGAS','JARDINS','SÃO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);

/* VAI DAR ERRO POR CAUSA DO UNIQUE*/
INSERT INTO ENDERECO VALUES(NULL,'RUA VIEIRA ALVES','NOSSA SENHORA','MANAUS','AM',5);

INSERT INTO TELEFONE VALUES(NULL,'CEL','36455698',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','56989659',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','85693254',2);
INSERT INTO TELEFONE VALUES(NULL,'CEL','96589765',6);
INSERT INTO TELEFONE VALUES(NULL,'CEL','12648796',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','98645689',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','56896589',6);
INSERT INTO TELEFONE VALUES(NULL,'COM','45896589',6);