CREATE DATABASE OFICINA;
USE OFICINA;

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE
);

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	ID_CARRO INT NOT NULL UNIQUE
);

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	PLACA VARCHAR(20) NOT NULL UNIQUE,
	ID_MARCA INT
);

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE CARRO_COR(
	ID_CARRO INT,
	ID_COR INT,
	PRIMARY KEY(ID_CARRO,ID_COR)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('CEL','RES','COM') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT
);

/* ADICIONANDO AS CHAVES */
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO) REFERENCES CARRO(IDCARRO);

ALTER TABLE CARRO ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA) REFERENCES MARCA(IDMARCA);

ALTER TABLE COR ADD CONSTRAINT FK_CARRO_COR
FOREIGN KEY(ID_CARRO) REFERENCES CARRO(IDCARRO);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CARRO_COR ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR) REFERENCES COR(IDCOR);

ALTER TABLE CARRO_COR ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO) REFERENCES CARRO(IDCARRO);

