/* PRIMEITA FORMA NORMAL 
	1 - TODO CAMPO VEOTRIZADO SE TORNARÁ OUTRA TABELA
	2 - TODO CAMPO MULTIVALORADO SE TORNARÁ OUTRA TABELA.
 QUANDO O CAMPO FOR DIVISÍVEL.
	3 - TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE 
	IDENTIFIQUE TODO O REGISTRO COMO SENDO ÚNICO. ISSE É
	QUE CHAMAMOS DE CHAVE PRIMÁRIA OU PRIMARY KEY.
*/
