/* DELIMITADOR */

DELIMITER $

SELECT * FROM V_RELATORIO$

/* STORES PROCEDURES */

SELECT "MAFRA";
/* É NECESSARIO MUDAR O DELIMITADOR POIS O ';' SERÁ USADO NOS PROCEDIMENTOS */
DELIMITER $

CREATE PROCEDURE NOME()
BEGIN
	QUALQUER PROGRAMAÇÃO;
END
$

CREATE PROCEDURE NOME_EMPRESA()
BEGIN
	SELECT 'UNIVERSIDADE DOS DADOS' AS EMPRESA;
END
$

/* CHAMANDO UMA PROCEDURE */
CALL NOME_EMPRESA()$

/* APAGANDO UMA PROCEDURE */
DROP PROCEDURE CONTA$

/* PROCEDURES COM PARAMETROS */
CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT)
BEGIN
	SELECT NUMERO1 + NUMERO2 AS CONTA;
END
$

CALL CONTA(100,50)$

SHOW DATABASES;
CREATE DATABASE ESCOLA;

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT(10,2) NOT NULL
);

SHOW TABLES;
DESC CURSOS;

INSERT INTO CURSOS VALUES(NULL, 'JAVA', 30, 500);
INSERT INTO CURSOS VALUES(NULL, 'FUNCDAMENTOS DE BANCO DE DADOS', 40, 700);

/* FAZER DUAS PROCEDURES
	1 - CADASTRAR
	2 - CONSULTAR*/

DELIMITER #

CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30), P_HORAS INT(3), P_PRECO FLOAT(10,2))
BEGIN
	INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_PRECO);
END
#

DELIMITER ;

CALL CAD_CURSO('BD SQL SERVER',35,3000);

SELECT * FROM CURSOS;

/*CRIAR A PROCEDURE DE CONSULTA*/