/*SUBQUERIES*/
/* VENDEDOR QUE VENDEU MENOS EM MARCO*/
SELECT NOME, MARCO FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);
 
 /* VENDEDOR QUE VENDEU MAIS EM MARCO*/
SELECT NOME, MARCO FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);

/* VENDEDOR QUE VENDEU MAIS QUE O VALOR MEDIO DE FEV*/ 
SELECT NOME, FERVEREIRO FROM VENDEDORES
WHERE FERVEREIRO > (SELECT AVG(FERVEREIRO) FROM VENDEDORES);
/*ALTERQUERIE E INNERQUERIE*/

SELECT NOME,
	   JANEIRO,
	   FEVEREIRO,
	   MARCO,
	   (JANEIRO+FERVEREIRO+MARCO) AS "TOTAL",
	   TRUNCATE((JANEIRO+FERVEREIRO+MARCO)/3,2) AS "MEDIA",