CREATE DATABASE CURSORES;
USE CURSORES;

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT
);

INSERT INTO VENDEDORES VALUES(NULL,'MARIA',32432,25684,35577);
INSERT INTO VENDEDORES VALUES(NULL,'CLARA',56952,98588,58965);
INSERT INTO VENDEDORES VALUES(NULL,'JOAO',23548,25784,12658);
INSERT INTO VENDEDORES VALUES(NULL,'LILIAN',59668,25888,85788);
INSERT INTO VENDEDORES VALUES(NULL,'FELIPE',12548,32568,78546);
INSERT INTO VENDEDORES VALUES(NULL,'SANDER',21455,26584,39977);

SELECT * FROM VENDEDORES;
SELECT NOME, (JAN+FEV+MAR) AS TOTAL, (JAN+FEV+MAR)/3 AS MEDIA FROM VENDEDORES;

CREATE TABLE VEND_TOTAL(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT,
	TOTAL INT,
	MEDIA INT
);

DELIMITER $

CREATE PROCEDURE INSEREDADOS()
BEGIN
	DECLARE FIM INT DEFAULT 0;
	DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT;
	DECLARE VNOME VARCHAR(50);
	DECLARE REGISTRO CURSOR FOR(
		SELECT NOME, JAN, FEV, MAR FROM VENDEDORES
	);
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM =1;
	
	OPEN REGISTRO;
	
	REPEAT
		FETCH REGISTRO INTO VNOME, VAR1, VAR2, VAR3;
		IF NOT FIM THEN
			SET VTOTAL = VAR1+VAR2+VAR3;
			SET VMEDIA = VTOTAL/3;
			
			INSERT INTO VEND_TOTAL VALUES(VNOME,VAR1,VAR2,VAR3,VTOTAL,VMEDIA);
		END IF;
	UNTIL FIM END REPEAT;
	CLOSE REGISTRO;
END
$
DELIMITER ;

SELECT * FROM VENDEDORES;
SELECT * FROM VEND_TOTAL;

CALL INSEREDADOS();
