/* ENTENDENDO TRIGGERS */

/* ESTRUTURA DE UMA TRIGGER */

CREATE TRIGGER NOME
BEFORE / AFTER INSERT/DELETE/UPDATE ON TABELA
FOR EACH ROW (PARA CADA LINHA)
BEGIN -> INICIO
		QUALQUER COMANDO SQL
END -> FIM

CREATE DATABASE AULA40;
USE AULA40;

CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30),
	SENHA VARCHAR(30)
);

CREATE TABLE BKP_USUARIO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDUSUARIO INT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30)
);

/* CRIANDO A TRIGGER */
DELIMITER $

CREATE TRIGGER BACKUP_USER
BEFORE DELETE ON USUARIO
FOR EACH ROW
BEGIN
	INSERT INTO BKP_USUARIO VALUES( NULL, OLD.IDUSUARIO, OLD.NOME, OLD.LOGIN);
END
$

INSERT INTO USUARIO VALUES(NULL, 'MARCIA','marcinha10', '1234');
DELETE FROM USUARIO WHERE IDUSUARIO = 2;

CREATE DATABASE LOJA;
USE LOJA;

CREATE TABLE PRODUTOS(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

CREATE DATABASE BACKUP_LOJA;
USE BACKUP_LOJA;

CREATE TABLE BKP_PRODUTOS(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

USE LOJA;

INSERT INTO BACKUP_LOJA.BKP_PRODUTOS VALUES(NULL,1000,'TESTE',0.0);

DELIMITER $

CREATE TRIGGER BACKUP
AFTER INSERT ON PRODUTOS
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_LOJA.BKP_PRODUTOS VALUES(NULL, NEW.IDPRODUTO, NEW.NOME, NEW.VALOR);
END
$

INSERT INTO PRODUTOS VALUES(NULL,'LIVRO MODELAGEM',50.00);
INSERT INTO PRODUTOS VALUES(NULL,'LIVRO BI',80.00);
INSERT INTO PRODUTOS VALUES(NULL,'LIVRO ORACLE',100.00);
INSERT INTO PRODUTOS VALUES(NULL,'LIVRO SQL SERVER',39.00);

CREATE TRIGGER BACKUP_PRODUT_DEL
BEFORE DELETE ON PRODUTOS
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_LOJA.BKP_PRODUTOS VALUES(NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR);
END
$

ALTER TABLE BACKUP_LOJA.BKP_PRODUTOS
ADD EVENTO CHAR(1);

DROP TRIGGER BACKUP_PRODUT_DEL;

CREATE TRIGGER BACKUP_PRODUT_DEL
BEFORE DELETE ON PRODUTOS
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_LOJA.BKP_PRODUTOS VALUES(NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR,'D');
END
$

DELETE FROM PRODUTOS WHERE IDPRODUTO=3;
SELECT * FROM BACKUP_LOJA.BKP_PRODUTOS;

/* TRIGGER DE AUDITORIA */
CREATE DATABASE AUDITORIA_LOJA;
USE AUDITORIA_LOJA;

CREATE TABLE PRODUTOS(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

/* QUANDO */
SELECT NOW();
/* QUEM */
SELECT CURRENT_USER();


CREATE DATABASE BACKUP_AUDITORIA;
USE BACKUP_AUDITORIA;

CREATE TABLE BKP_PRODUTOS(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR(30),
	VALOR_ORIGINAL FLOAT(10,2),
	VALOR_ALTERADO FLOAT(10,2),
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO CHAR(1)
);

USE AUDITORIA_LOJA;

DELIMITER $

CREATE TRIGGER AUDIT_PROD
AFTER UPDATE ON PRODUTOS
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AUDITORIA.BKP_PRODUTOS VALUES(NULL,OLD.IDPRODUTO,OLD.NOME,OLD.VALOR,NEW.VALOR,NOW(),CURRENT_USER(),'U');
END
$

DELIMITER ;
USE AUDITORIA_LOJA;
UPDATE PRODUTOS SET VALOR = 110.00
WHERE IDPRODUTO = 4;
SELECT * FROM PRODUTOS;
SELECT * FROM BACKUP_AUDITORIA.BKP_PRODUTOS;